/** @type {import('tailwindcss').Config} */
import daisyui from "daisyui";

module.exports = {
    content: ["./src/**/*.{js,jsx,ts,tsx}"],
    theme: {
        extend: {
            keyframes: {
                fadeIn: {},
            },
            animation: {
                fadeIn: "fadeIn 0.3s ease-out forwards",
            },
        },
    },
    plugins: [daisyui],
    // darkMode: "class",
    daisyui: {
        // styled: true,
        themes: [
            "light",
            "dark",
            "cupcake",
            "bumblebee",
            "emerald",
            "corporate",
            "synthwave",
            "retro",
            "cyberpunk",
            "valentine",
            "halloween",
            "garden",
            "forest",
            "aqua",
            "lofi",
            "pastel",
            "fantasy",
            "wireframe",
            "black",
            "luxury",
            "dracula",
            "cmyk",
            "autumn",
            "business",
            "acid",
            "lemonade",
            "night",
            "coffee",
            "winter",
            "dim",
            "nord",
            "sunset",
        ],
        // base: true,
        // utils: true,
        // logs: false,
        // rtl: false,
        // prefix: "",
    },
};
